version: '3.9'

services:
  tx-generator:
    build:
      context: .. #./Dockerfile Path
      target: "tx-generator"
    environment:
      # Change Environment for test (Using QA)
      DUMMY_TX_TYPE: 2
      DUMMY_TX_ACC_PRIV_KEY: "${DUMMY_TX_ACC_PRIV_KEY}"
      DUMMY_TX_SEND_INTERVAL: 0.04s # 1s / 0.04 = 25 txs per sec, approximately 50 txs per block
      CHAIN_ID: 7791

      # Don't Change Environment
      VALIDATOR_OUTPUT_SUBMITTER_ENABLED: "true" # Output submitter
      VALIDATOR_CHALLENGER_ENABLED: "false"      # Challenger

      VALIDATOR_L1_ETH_RPC: "wss://wc.easel.kroma.cc" # Target to L1 Geth Client RPC (Easel)
      VALIDATOR_L2_ETH_RPC: "http://dev-kroma-sail-apne2-proposer-vanilla-0.kroma.cc:8545" # Target to L2 Geth Client RPC (Sail)
      VALIDATOR_ROLLUP_RPC: "http://dev-kroma-sail-apne2-vanilla-0.kroma.cc:9545" # Target to L2 Consensus Client (Full Node)
      VALIDATOR_CHALLENGER_POLL_INTERVAL: 5s

      # Secret Configs
      VALIDATOR_L2OO_ADDRESS: "0x74Cf9087AD26D541930BaC724B7ab21bA8F00a27"
      VALIDATOR_COLOSSEUM_ADDRESS: "0x88D1aF96098a928eE278f162c1a84f339652f95b"
      VALIDATOR_VALPOOL_ADDRESS: "0x8bCe54ff8aB45CB075b044AE117b8fD91F9351aB"

      # Secret Configs
      VALIDATOR_MNEMONIC: "wonder paper game grace consider pizza grain judge stadium street nothing elevator"
      VALIDATOR_HD_PATH: "m/44'/60'/1'/0/21" # QA 7~14 devops 0~6
