version: '3.9'

services:
  validator:
    image: kromanetwork/validator:v1.0.0-rc.2
    environment:
      # Change Environment for test (Using QA)
      VALIDATOR_OUTPUT_SUBMITTER_ENABLED: "false" # Output submitter
      VALIDATOR_CHALLENGER_ENABLED: "true"        # Challenger

      # Don't Change Environment
      VALIDATOR_L1_ETH_RPC: "wss://eth-mainnet.g.alchemy.com/v2/0Kr6zOZd1yIhSencs7lilltsBuog9vFR" # Target to L1 Geth Client RPC (Easel)
      VALIDATOR_L2_ETH_RPC: "https://api.kroma.network" # Target to L2 Geth Client RPC (Sail)
      VALIDATOR_ROLLUP_RPC: "http://apne2a-mainnet-proposer01.kroma.network:9545" # Target to L2 Consensus Client (Full Node)
      VALIDATOR_METRICS_ENABLED: "true"
      VALIDATOR_ALLOW_NON_FINALIZED: "true"
      VALIDATOR_TXMGR_TX_SEND_TIMEOUT: 600s
      VALIDATOR_NUM_CONFIRMATIONS: "1"
      VALIDATOR_SAFE_ABORT_NONCE_TOO_LOW_COUNT: "3"
      VALIDATOR_RESUBMISSION_TIMEOUT: 30s
      VALIDATOR_LOG_TERMINAL: "true"
      VALIDATOR_PPROF_ENABLED: "true"
      VALIDATOR_PROVER_RPC: "http://apne2a-mainnet-prover-proxy.kroma.network:6000"
      VALIDATOR_CHALLENGER_POLL_INTERVAL: 5s
      VALIDATOR_GUARDIAN_ENABLED: "false"
      VALIDATOR_FETCHING_PROOF_TIMEOUT: 14400s

      # Secret Configs
      VALIDATOR_L2OO_ADDRESS: "0x35bDDC8dE48590769838B27fce99BA1bA79332c2"
      VALIDATOR_COLOSSEUM_ADDRESS: "0xe0c328959C579d5078aa13841A9003543A4d43f9"
      VALIDATOR_VALPOOL_ADDRESS: "0xfdc4be24fF4B5FEFCF5a81ecC51027F8Ae56aF8d"
      VALIDATOR_SECURITYCOUNCIL_ADDRESS: "0xFae3De0162dEBD7964dc71150B711ebf6A80aA02"
      VALIDATOR_PRIVATE_KEY: "${PRIVATE_KEY}"