version: '3.9'

services:
  validator:
    image: kromanetwork/validator:v1.0.1-rc.1
    environment:
      # Change Environment for test (Using QA)
      VALIDATOR_OUTPUT_SUBMITTER_ENABLED: "false" # Output submitter
      VALIDATOR_CHALLENGER_ENABLED: "true"        # Challenger

      # Don't Change Environment
      VALIDATOR_L1_ETH_RPC: "wss://wc.easel.kroma.cc" # Target to L1 Geth Client RPC (Easel)
      VALIDATOR_L2_ETH_RPC: "http://apne2a-sail-proposer01.kroma.cc:8545" # Target to L2 Geth Client RPC (Sail)
      VALIDATOR_ROLLUP_RPC: "http://apne2a-sail-proposer01.kroma.cc:9545" # Target to L2 Consensus Client (Full Node)
      VALIDATOR_METRICS_ENABLED: "true"
      VALIDATOR_ALLOW_NON_FINALIZED: "true"
      VALIDATOR_TXMGR_TX_SEND_TIMEOUT: 600s
      VALIDATOR_NUM_CONFIRMATIONS: "1"
      VALIDATOR_SAFE_ABORT_NONCE_TOO_LOW_COUNT: "3"
      VALIDATOR_RESUBMISSION_TIMEOUT: 30s
      VALIDATOR_LOG_TERMINAL: "true"
      VALIDATOR_PPROF_ENABLED: "true"
      VALIDATOR_PROVER_RPC: "http://43.200.68.65:6000"
      VALIDATOR_CHALLENGER_POLL_INTERVAL: 5s
      VALIDATOR_GUARDIAN_ENABLED: "false"
      VALIDATOR_FETCHING_PROOF_TIMEOUT: 14400s

      # Secret Configs
      VALIDATOR_L2OO_ADDRESS: "0x81F82957608f74441E085851cA5Cc091b23d17A2"
      VALIDATOR_COLOSSEUM_ADDRESS: "0x5BFaaA02cAb795d576276a19CB1c2D2D2d652717"
      VALIDATOR_VALPOOL_ADDRESS: "0x645D817611E0CDaF9cD43332c4E369B9E333471d"
      VALIDATOR_SECURITYCOUNCIL_ADDRESS: "0xa51807d5a12E7e78148c66dC4851CD33EEd1FDfD"
      VALIDATOR_MNEMONIC: "wonder paper game grace consider pizza grain judge stadium street nothing elevator"
      VALIDATOR_HD_PATH: "${HD_PATH}" # QA 7~14 devops 0~6
